version: '2'

services:

  dev:
    image: datadog/dev:base
    build: dev
    volumes:
      - .:/opt/project
      - ./src/datadog-mock:/go/src/jancajthaml/datadog-mock
    working_dir: /go/src/jancajthaml/datadog-mock
    environment:
      - GOPATH=/go
    entrypoint: /bin/sh
    privileged: true

  sync:
    extends: dev
    image: datadog/dev:sync
    entrypoint: ["/opt/project/dev/lifecycle/sync"]

  fmt:
    extends: dev
    image: datadog/dev:fmt
    entrypoint: gofmt
    command: ["-w", "."]

  lint:
    extends: dev
    image: datadog/dev:lint
    entrypoint: go
    command: ["vet", "./..."]

  package:
    extends: dev
    image: datadog/dev:package
    entrypoint: ["/opt/project/dev/lifecycle/package"]

  test:
    extends: dev
    image: datadog/dev:sync
    entrypoint: ["/opt/project/dev/lifecycle/test"]

  artefact:
    restart: unless-stopped
    image: datadog/mock:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8125:8125/udp"
